// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1I6lWbFn0Gjyhf-DK-saukbKLUeIpgtk',
    appId: '1:896352111388:web:98fd979eae531b5ced08d9',
    messagingSenderId: '896352111388',
    projectId: 'fcmmsgflutter',
    authDomain: 'fcmmsgflutter.firebaseapp.com',
    storageBucket: 'fcmmsgflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWkN1w6g1cVBs2g1vySduNIVLv5L0A_aY',
    appId: '1:896352111388:android:135776088cdd7b7bed08d9',
    messagingSenderId: '896352111388',
    projectId: 'fcmmsgflutter',
    storageBucket: 'fcmmsgflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChPoiCPG9bmKBsjAlp1JzfCSa5UWyWQG8',
    appId: '1:896352111388:ios:de75d4c56f88b94fed08d9',
    messagingSenderId: '896352111388',
    projectId: 'fcmmsgflutter',
    storageBucket: 'fcmmsgflutter.appspot.com',
    iosClientId: '896352111388-n9mpc6epcvcnh560vo9rj0m6seapcc7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.fcmFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChPoiCPG9bmKBsjAlp1JzfCSa5UWyWQG8',
    appId: '1:896352111388:ios:de75d4c56f88b94fed08d9',
    messagingSenderId: '896352111388',
    projectId: 'fcmmsgflutter',
    storageBucket: 'fcmmsgflutter.appspot.com',
    iosClientId: '896352111388-n9mpc6epcvcnh560vo9rj0m6seapcc7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.fcmFlutter',
  );
}
